### ISSUE TITLE
Support Pi 0.87.0: type surface + compaction eligibility (follow-up to #117)

### ISSUE THREAD

**Issue by k0valik** [k0valik/pi-blackhole#118]
# Support Pi 0.87.0 (type surface + compaction eligibility)

Follow-up to #117. That issue is only the compact-shape guard and has a small, independent fix. This issue covers **everything else** that breaks when the `@earendil-works/*` devDependencies move to `0.87.0` — found while validating #117 against the real 0.87.0 package (not fixtures).

Status: `0.87.0` is held out of the automatic bump in `.github/dependabot.yml`; remove those `ignore` entries once this is fixed.

## Reproduction

```bash
git worktree add /tmp/pi087 --detach origin/dev
cd /tmp/pi087
# 0.87.0 was published 2026-09-21; the 48h maturity gate blocks it, so bypass it
PNPM_CONFIG_MINIMUM_RELEASE_AGE=0 pnpm install --frozen-lockfile
PNPM_CONFIG_MINIMUM_RELEASE_AGE=0 pnpm add -D \
  @earendil-works/pi-agent-core@0.87.0 @earendil-works/pi-ai@0.87.0 \
  @earendil-works/pi-coding-agent@0.87.0 @earendil-works/pi-tui@0.87.0
PNPM_CONFIG_MINIMUM_RELEASE_AGE=0 pnpm typecheck
PNPM_CONFIG_MINIMUM_RELEASE_AGE=0 pnpm test
```

Observed on 0.87.0 (with the #117 guard fix applied, to see past it): **5 type errors, 5 test failures.** Without the guard fix it is 11 test failures — the extra 6 are #117.

## 1. `AgentContext` no longer has `systemPrompt` (3 errors)

```
src/om/agents/dropper/agent.ts(350,5): error TS2353: Object literal may only specify known properties, and 'systemPrompt' does not exist in type 'AgentContext'.
src/om/agents/observer/agent.ts(259,5): error TS2353: (same)
src/om/agents/reflector/agent.ts(178,5): error TS2353: (same)
```

All three OM agent loops build `{ systemPrompt, messages, tools }`:

```ts
const context: AgentContext = {
  systemPrompt: DROPPER_SYSTEM,
  messages: [],
  tools: [dropObservations as AgentTool<any>],
};
```

`pi-agent-core@0.87.0` still has a `readonly systemPrompt: string` somewhere (`dist/types.d.ts:332`) and its `Agent` docs mention "`systemPrompt` and `tools` become the leading system message unless `messages` already starts with one", so this is a reshape/rename of `AgentContext`, not a removal of the concept. Need to find the new carrier for the system prompt and update the three call sites.

## 2. Compaction eligibility changed (4 test failures)

```
FAIL tests/compaction-trigger.test.ts > Eligibility guard (...) > deferred recheck skips compaction when session becomes ineligible before agent settles
FAIL tests/compaction-trigger.test.ts > Eligibility guard (...) > resumes auto-compaction after history grows past keepRecentTokens
FAIL tests/compaction-trigger.test.ts > Eligibility guard (...) > respects effective configured keepRecentTokens rather than a hardcoded 20k
FAIL tests/compaction-trigger.test.ts > Eligibility guard (...) > genuine compaction errors remain visible when eligible compaction fails
```

This one is **not** a fixture artifact and **not** caused by #117:

* the describe block's `beforeEach` calls `installHostInlineCompactionAdapter({ entrypoint: node_modules/@earendil-works/pi-coding-agent/dist/bundle/cli.js })`, so `isCompactionEligible()` delegates to the **real** host `prepareCompaction`;
* the failures reproduce in isolation (`pnpm vitest run tests/compaction-trigger.test.ts -t "<one test>"`), so it is not registry leakage between tests;
* it fails identically with and without the #117 guard fix.

`prepareCompaction`'s signature is unchanged (`prepareCompaction(pathEntries, settings)` in both 0.85.1 and 0.87.0), so **0.87 changed the eligibility semantics**: it now returns `undefined` for small branches that 0.85/0.86 treated as eligible. That affects auto-compaction for every 0.87 user, independent of the inline adapter.

Open questions: is the eligible set now smaller by design (new cut-point/`keepRecentTokens` handling, new entry types like `context_edit`), or is this a regression upstream? Worth diffing `dist/core/compaction/compaction.js` between 0.85.1 and 0.87.0 and/or asking upstream.

## 3. Extension API double drift (1 test failure)

```
FAIL tests/pi-extension-api.test.ts > extension API double > preserves callback argument types through capture and replay
```

The fixture typechecks `tests/fixtures/pi-extension-api.ts` against the installed pi types:

```
tests/fixtures/pi-extension-api.ts(24,5): error TS2322: Type '(...[event, handler]: [event: "turn_end", handler: ExtensionHandler<TurnEndEvent>] | [event: ... 33 more ...]) => void' is not assignable to type '{ (event: "project_trust", handler: ProjectTrustHandler): () => void; ... }'.
  Type 'void' is not assignable to type '() => void'.
```

`ExtensionAPI.on()`'s overloads/handler return type changed in 0.87 (handlers appear to now be expected to return the unsubscribe function). Needs the double and/or the fixture updated to the 0.87 contract.

## 4. pi-ai message union drift (2 errors)

```
src/hooks/cosmetic-output.ts(121,31): error TS2367: This comparison appears to be unintentional because the types '"toolResult"' and '"assistant"' have no overlap.
src/hooks/cosmetic-output.ts(122,17): error TS2339: Property 'stopReason' does not exist on type 'never'.
```

The narrowed message union in `pi-ai@0.87.0` no longer reaches `assistant` on that branch. Needs the narrowing redone against the new union.

## What already works on 0.87.0

* Launcher/host discovery is unaffected — same `dist/bundle/cli.js` → `createRequire("./cli-runtime.js")` → `chunks/chunk-*.js` layout as 0.86 (see #116).
* `dist/core/compaction/{index,compaction}.js` still exists and still exports `prepareCompaction`, so `resolveHostPrepareCompaction` resolves.
* Every runtime hook the inline adapter depends on is present: `_bindExtensionCore`, `compact()` calling `this.abort()` exactly once, `appendCompaction`, the `agent.state.messages` repoint (via `_refreshFinalizedContext()`), `buildSessionContext`, `_compactionAbortController`, `prepareNextTurnWithContext`, `_disconnectFromAgent` (present, not called from `compact()`).

## Suggested split

1. Land the #117 guard fix (small, independent, makes the 6 masked failures pass).
2. Then this: types first (§1, §4), extension-API double (§3), and the eligibility investigation (§2) last since it may need an upstream answer.
3. Remove the `@earendil-works/*` `>=0.87.0` ignore from `.github/dependabot.yml` as part of the bump PR.
